name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "latest"

      - name: 🛠️ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧪 Run fmt check
        run: pnpm prettier --check .

      - name: 🧪 Run test
        run: pnpm test
